name: Auto Commit

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make changes
        run: |
          git config user.name "BUTInfo"
          git config user.email "butinfo@example.com"
          # your code that modifies files
          git add .
          git commit -m "Mise à jour automatique du fichier ICS" || echo "No changes"

      - name: Push changes
        run: git push
