name: Update ICS

on:
  schedule:
    - cron: '0 5 * * *'  # Tous les jours à 6h heure France (UTC+1/UTC+2)
  workflow_dispatch:     # Permet aussi de lancer manuellement

jobs:
  update-ics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Télécharger le ICS
        run: |
          curl -L "https://edt.univ-lyon1.fr/jsp/custom/modules/plannings/anonymous_cal.jsp?resources=31184,12444,12424&projectId=1&calType=ical&firstDate=2025-08-18&lastDate=2026-08-01" -o edt.ics

      - name: Commit et push
        run: |
          git config user.name "BUTInfo"
          git config user.email "t.meheust2007@gmail.com"
          git add edt.ics
          git commit -m "Mise à jour automatique du fichier ICS" || echo "Pas de modification"
          git push
